apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
	app: app
  strategy: {}
  template:
    metadata:
	creationTimestamp: null
	labels:
	  app: app
    spec:
      containers:
      - image: virt.01
	imagePullPolicy: IfNotPresent
	name: virt-01-42lsz
	resources: {}
	env:
	- name: NAME
	  valueFrom:
	    configMapKeyRef:
		name: config
		key: name


status: {}
